name: Raito CLI - Azure Plugin - Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  GOPRIVATE: "github.com/raito-io/*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Configure git for private modules
        run: git config --global url."https://${{secrets.CI_SECRETS_TOKEN_USER}}:${{secrets.CI_SECRETS_TOKEN}}@github.com".insteadOf "https://github.com"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CI_SECRETS_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{github.ref_name}}
